[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
watchPatterns = ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "prisma/**/*"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.staging]
[environments.staging.variables]
NODE_ENV = "staging"
NEXTAUTH_URL = "https://fundbio-staging.railway.app"
ALLOWED_ORIGINS = "https://fundbio-staging.railway.app"

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
NEXTAUTH_URL = "https://fundbio.railway.app"
ALLOWED_ORIGINS = "https://fundbio.railway.app"

[services.web]
type = "web"
domains = ["fundbio.railway.app"]
port = 3000

[services.database]
type = "postgresql"
[services.database.variables]
POSTGRES_DB = "fundbio_dashboard"
POSTGRES_USER = "fundbio_user"

[services.redis]
type = "redis"
[services.redis.variables]
REDIS_URL = "redis://redis:6379"